heda

diff --git a/.config/hypr/scripts/wal-dark b/.config/hypr/scripts/wal-dark
--- a/.config/hypr/scripts/wal-dark
+++ b/.config/hypr/scripts/wal-dark
@@ -4,10 +4,10 @@
 GREEN='\033[1;32m'
 NC='\033[0m' # No Color
 GLYPH='󰏘'
-# Genereting Wal color 
+# Genereting Wal color
 
 echo -e "\n${GREEN}${GLYPH} Genereting Pywal colors.${NC}"
-wal -i $(swww query | awk -F 'image: ' '{print $2}')
+wal -i "$(swww query | head -1 | awk -F 'image: ' '{print $2}')"
 
 # Directory containing PNG files
 icon_dir="$HOME/.config/hypr/scripts/icons/"
@@ -19,12 +19,12 @@ icons=("$icon_dir"pywal-*.png)
 
 # Check if there are PNG files
 if [ ${#icons[@]} -eq 0 ]; then
-    echo -e "${GREEN}${GLYPH} Error: No PNG files found in $icon_dir${NC}"
-    exit 1
+  echo -e "${GREEN}${GLYPH} Error: No PNG files found in $icon_dir${NC}"
+  exit 1
 fi
 
 # Choose a random icon
-random_index=$(( RANDOM % ${#icons[@]} ))
+random_index=$((RANDOM % ${#icons[@]}))
 icon=${icons[$random_index]}
 echo -e "${GREEN}${GLYPH} Selected icon: $icon${NC}"
 
@@ -37,8 +37,8 @@ palette_icon="$icon_dir/palette.png"
 
 # Check if palette.png exists
 if [ ! -f "$palette_icon" ]; then
-    echo -e "${GREEN}${GLYPH} Error: palette.png not found in $icon_dir${NC}"
-    exit 1
+  echo -e "${GREEN}${GLYPH} Error: palette.png not found in $icon_dir${NC}"
+  exit 1
 fi
 
 echo -e "${GREEN}${GLYPH} Sending notification with icon: $palette_icon${NC}"
@@ -62,7 +62,7 @@ python ~/.config/hypr/scripts/colors-folders.py
 
 echo -e "\n${GREEN}${GLYPH} Building Qt theme with script build-qt ${NC}"
 ~/.config/hypr/scripts/build-qt
-~/.config/hypr/scripts/build-qt6 
+~/.config/hypr/scripts/build-qt6
 
 echo -e "\n${GREEN}${GLYPH} Building kvuntum theme with script build-kvuntum ${NC}"
 python ~/.config/hypr/scripts/build-kvantum.py
@@ -79,12 +79,12 @@ echo -e "\n${GREEN}${GLYPH} Running zed-theme (for Zed) ${NC}"
 echo -e "\n${GREEN}${GLYPH} Script execution completed.${NC}"
 
 # Randomly decide whether to show the "Did you notice?" notification
-show_notice=$(( RANDOM % 5 ))  # 20% chance
+show_notice=$((RANDOM % 5)) # 20% chance
 
 if [ $show_notice -eq 0 ]; then
-    # Choose a new random icon
-    random_index=$(( RANDOM % ${#icons[@]} ))
-    icon=${icons[$random_index]}
-    echo -e "${GREEN}${GLYPH} Sending 'Did you notice?' notification with icon: $icon${NC}"
-    notify-send -i "$icon" -e -h string:x-canonical-private-synchronous:sys-notify -u low -t 10000 "Did you notice?" "The notification icon has changed!"
+  # Choose a new random icon
+  random_index=$((RANDOM % ${#icons[@]}))
+  icon=${icons[$random_index]}
+  echo -e "${GREEN}${GLYPH} Sending 'Did you notice?' notification with icon: $icon${NC}"
+  notify-send -i "$icon" -e -h string:x-canonical-private-synchronous:sys-notify -u low -t 10000 "Did you notice?" "The notification icon has changed!"
 fi
